{
    "codecov": {
        "require_ci_to_pass": true
    },
    "comment": false,
    "parsers": {
        "gcov": {
            "branch_detection": {
                "loop": true,
                "macro": false,
                "method": false,
                "conditional": true
            }
        },
        "javascript": {
            "enable_partials": false
        }
    },
    "coverage": {
        "range": [
            70,
            100
        ],
        "round": "down",
        "status": {
            "patch": {
                "default": {
                    "target": "auto",
                    "threshold": 1
                }
            },
            "changes": false,
            "project": {
                "default": {
                    "target": "auto",
                    "threshold": 1
                }
            }
        },
        "precision": 2
    }
}
