on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
      - develop
  pull_request:
    branches:
      - main
      - master
      - develop

name: lint

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-r-dependencies@v1
        with:
          extra-packages: lintr
      - name: Install package
        run: R CMD INSTALL .
      - name: Lint
        run: lintr::lint_package()
        shell: Rscript {0}
