on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

name: codecov

jobs:
  codecov:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1
      - uses: r-lib/actions/setup-r-dependencies@v1
        with:
          extra-packages: covr
      - name: Install Package
        run: R CMD INSTALL --install-tests .
      - name: Coverage Report
        run: |
          covr::codecov()
        shell: Rscript {0}
